var http = require('http');
var fs = require('fs');
var url = require('url');
var axios = require('axios');

function genFilmes(dados) {
    filmes = dados
    pagHtml = `<!DOCTYPE html>
    <html>
        <head>
            <meta charset="utf-8">
            <title>Lista de Filmes</title>
            <link rel="stylesheet" href="/w3.css"/>
        </head>
        <body>
            <div class="w3-card-4">
    
                <header class="w3-container w3-blue">
                  <h1>Lista de Filmes</h1>
                </header>
                
                <div class="w3-container">
                    <table class="w3-table w3-striped w3-bordered">
                        <tr>
                            <th>Titulo</th>
                            <th>Ano</th>
                        </tr>
    `
    filmes.forEach(ocorr => {
        pagHtml += `
                            <tr>
                                <td><a href = '/filmes/${ocorr.id}'>${ocorr.title}</a></td>
                                <td>${ocorr.year}</td>
                            </tr>
    `
    });

    pagHtml += `
                    </table>
                    </div>

                    <footer class="w3-container w3-blue">
                      <h5>Generated by EngWeb2024</h5>
                    </footer>

                </div>
        </body>
    </html>
    `
    return pagHtml
}


function genFilme_id (id_filme, dados){
    var filme = dados.find(f => f.id == id_filme)
    if (!filme) {
        console.log(`No film found with id ${id_filme}`)
        return
    }
    pagHtml = `<!DOCTYPE html>
    <html>
        <head>
            <meta charset="utf-8">
            <title>${filme.title}</title>
            <link rel="stylesheet" href="/w3.css"/>
        </head>
        <body>
            <div class="w3-card-4">
    
                <header class="w3-container w3-blue">
                  <h1>${filme.title}</h1>
                </header>
                
                <div class="w3-container">
                    <table class="w3-table w3-striped w3-bordered">
                        <tr>
                            <th>Titulo</th>
                            <th>Ano</th>
                            <th>Elenco</th>
                            <th>Genero</th>
                        </tr>
                            <tr>
                                <td>${filme.title}</td>
                                <td>${filme.year}</td>
                                <td>${filme.cast}</td>
                                <td>${filme.genres}</td>
                            </tr>
                    </table>
                    </div>

                    <footer class="w3-container w3-blue">
                      <h5>Generated by EngWeb2024</h5>
                    </footer>

                </div>
        </body>
    </html>
    `
    return pagHtml
}





http.createServer(function (req, res) {
    var id_filmexp = /\/filmes\/\w+$/
    var q = url.parse(req.url, true)
    if(q.pathname == '/') {
        fs.readFile('Pagina_inicial.html', function(erro, data) {
            res.writeHead(200, {'Content-Type': 'text/html'})
            res.write(data)
            res.end()
        })
    }
    else if(q.pathname == '/filmes') {
        axios.get('http://localhost:3000/filmes')
        .then(function(response) {
            dados = response.data
            pagHtml = genFilmes(dados)
            res.writeHead(200, {'Content-Type': 'text/html'})
            res.write(pagHtml)
            res.end()
        })
        .catch(function(error) {
            console.log(error)
        })
    }
    else if(id_filmexp.test(q.pathname)) {
        console.log('q.pathname: ' + q.pathname)
        var id_filme = q.pathname.substring(8)
        console.log('id_filme: ' + id_filme)
        axios.get('http://localhost:3000/filmes/')
            .then(function(response) {
                dados = response.data
                pagHtml = genFilme_id(id_filme, dados)
                res.writeHead(200, {'Content-Type': 'text/html'})
                res.write(pagHtml)
                res.end()
            })
            .catch(function(error) {
                console.log(error)
            })
    }
    else if(q.pathname == '/w3.css') {
        fs.readFile('w3.css', function(erro, data) {
            res.writeHead(200, {'Content-Type': 'text/css'})
            res.write(data)
            res.end()
        })
    }
    else {
        res.writeHead(400, {'Content-Type': 'text/html; charset=utf-8'})
        res.write('<p>Pedido não suportado.</p>')
        res.write('<pre>' + q.pathname + '</pre>')
        res.end()
    }
    console.log(q.pathname)
}).listen(7777)