import os
import xml.etree.ElementTree as ET 

bd = []
for file in os.listdir("texto"):
    numero = ""  # Initialize numero
    nome = ""  # Initialize nome
    # criar um tuplo imagem, legenda
    imagem = ""
    legenda = ""
    figura = []
    tree = ET.parse("texto/"+file)
    root = tree.getroot()

    if file.endswith(".xml"):
        for child in root:
            if child.tag == "meta":
                for meta in child:
                    if meta.tag == "número":
                        numero = meta.text
                    if meta.tag == "nome":
                        nome = meta.text
            if child.tag == "corpo":
                for corpo in child:
                    if corpo.tag == "figura":
                        for fig in corpo:
                            if fig.tag == "imagem":
                                imagem =  "../MapaRuas-materialBase" + fig.attrib['path'][2:]
                            if fig.tag == "legenda":
                                legenda = fig.text
                        figura.append((imagem, legenda))
        bd.append((file[:-4], numero, nome, figura))


bd.sort(key=lambda x: int(x[1]))



for e in bd:
    f = open('../Ruas_site/'+ e[0] + '.html', "w")
    poshtml = f"""
<!DOCTYPE html>
<html>
<head>
    <title>{e[2]}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="w3.css">
    <meta charset="utf-8"/>
</head>
<body>
    <div class="w3-card-4">
        <header class="w3-container w3-purple">
            <h1>{e[2]}</h1>
        </header>

        <div class="w3-container w3-center">
            <h3>Vistas</h3>
        </div>

        <div class="w3-row-padding w3-margin-top">
    """
    
    for fig in e[3]:
        poshtml += f"""
            <div class="w3-third">
                <div class="w3-card">
                    <img src="{fig[0]}" style="width:100%">
                    <div class="w3-container">
                        <h5>{fig[1]}</h5>
                    </div>
                </div>
            </div>
        """

    prehtml = f"""
        </div>

        <div class="w3-container w3-center">
            <h3>Descrição</h3>
        </div>

        <p>Descrição da rua</p>
        <br></br>
        <footer class="w3-container w3-purple">
            <h5>Generated by EMDApp::EngWeb2024::a95319</h5>
        </footer>            
    </div>
</body>
</html> 
    """

    paghtml = poshtml + prehtml
    
    f.write(paghtml)
    f.close()
