import os
import xml.etree.ElementTree as ET 

preHTML = """
<!DOCTYPE html>
<html>
    <head>
        <title>Lista de Ruas de Braga</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="w3.css">
        <link rel="stylesheet" href="style.css">
        <meta charset="utf-8"/>
    </head>
    <body>
        <div class="w3-card-4">
            <header class="w3-container w3-grey">
              <h1>Lista de Ruas de Braga</h1>
            </header>
            
            <div class="w3-container">
                <ul class="w3-ul w3-card-4" style="width:50%">
"""

posHTML = """
                </ul>
            </div>
            <footer class="w3-container w3-grey">
                <h5>Generated by EMDApp::EngWeb2024::a95319</h5>
            </footer>            
        </div>
    </body>
</html> 
"""

nomes_numeros = []

# ler os ficheiros xml do diretorio texto e adicionar os nomes das ruas a lista_nomes
for file in os.listdir("texto"):
    if file.endswith(".xml"):
        tree = ET.parse("texto/"+file)
        root = tree.getroot()
        numero = ""  # Initialize numero
        nome = ""  # Initialize nome
        for child in root:
            if child.tag == "meta":
                for meta in child:
                    if meta.tag == "número":
                        numero = meta.text
                    if meta.tag == "nome":
                        nome = meta.text
        nomes_numeros.append((numero, nome,file[:-4]))

# ordenar a lista de nomes_numeros por numero
nomes_numeros.sort(key=lambda x: int(x[0]))


conteudo = ""


for rua in nomes_numeros:
    conteudo += f"""
                    <li>
                        <a href="{rua[2]}.html">
                            {rua[0] + "." + rua[1]}</a>
                    </li>
    """

paghtml = preHTML + conteudo + posHTML

f = open("../Ruas_site/index.html", "w")
f.write(paghtml)
f.close()



































