import json, os

f = open("mapa-virtual.json", "r")
db = json.load(f)


# Criação do index.html
preHTML = """
<!DOCTYPE html>
<html>
    <head>
        <title>Cidades de Portugal</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="w3.css">
        <link rel="stylesheet" href="style.css">
        <meta charset="utf-8"/>
    </head>
    <body>
        <div class="w3-card-4">
            <header class="w3-container w3-grey">
              <h1>Cidades de Portugal</h1>
            </header>
            
            <div class="w3-container">
                <ul class="w3-ul w3-card-4" style="width:50%">
"""

btHTML = """"""

for dados in db["cidades"]:
    id = dados["id"]
    nome = dados["nome"]
    if (id[0] == "c"):
        btHTML += f"""
                    <li><a href="http://localhost:7777/{id}">{nome}</a></li> """


posHTML = """
                 </ul>
            </div>
            <footer class="w3-container w3-grey">
                <h5>Generated by EMDApp::EngWeb2024::a95319</h5>
            </footer>            
        </div>
    </body>
</html> 
"""

Index_HTML = preHTML + btHTML + posHTML

f = open("Paginas/index.html", "w")
f.write(Index_HTML)
f.close()


def city_name(id):
    for cidade in db["cidades"]:
        if (cidade["id"] == id):
            return cidade["nome"]


# Criação das páginas individuais
for cidade in db["cidades"]:
    html_pre = f"""
<!DOCTYPE html>
<html>
    <head>
        <title>{cidade["nome"]}</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="w3.css">
        <link rel="stylesheet" href="style.css">
        <meta charset="utf-8"/>
    </head>
    <body>
        <div class="w3-card-4">
            <header class="w3-container w3-grey">
              <h1>{cidade["nome"]}</h1>
            </header>
            
            <div class="w3-round-xlarge w3-grey">
                <p><b>Nome:</b> {cidade["nome"]}</p>
            </div>

            <div class="w3-round-xlarge w3-grey">
                <p><b>ID:</b> {cidade["id"]}</p>
            </div>

            <div class="w3-round-xlarge w3-grey">
                <p><b>População:</b> {cidade["população"]}</p>
            </div>

            <div class="w3-round-xlarge w3-grey">
                <p><b>Distrito:</b> {cidade["distrito"]}</p>
            </div>

            <div class="example">
                <div class="w3-container w3-center">
                <h3><b>Descrição</b></h3>
                </div>
                <p>{cidade["descrição"]}</p>
            </div>
            <div class="w3-container w3-center">
                <h3><b>Ligações</b></h3>
              </div>
            <table class="w3-table-all">
                <tr class="w3-grey">
                    <th>ID</th>
                    <th>Destino</th>
                    <th>Distância</th>
                </tr>
"""

    for ligacao in db["ligacoes"]:
        if (ligacao["origem"] == cidade["id"]):
            html_pre += f"""
                <tr>
                    <td>{ligacao["id"]}</td>
                    <td><a href="http://localhost:7777/{ligacao["destino"]}">{city_name(ligacao["destino"])}</a></td>
                    <td>{ligacao["distância"]}</td>
                </tr>
"""
    
    html_pos = """
            </table>
        </div>
        </p>
    <footer class="w3-container w3-grey">
        <h5>Generated by EMDApp::EngWeb2024::a95319</h5>
    </footer>            
</div>
</body>
</html> 
"""

    HTML = html_pre + html_pos
    f1 = open(f"Paginas/{cidade['id']}.html", "w")
    f1.write(HTML)
    f1.close()
            
    