exports.mainPage = function () {
    var html = `
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Pagina Inicial</title>
        <link rel="icon" href="favicon.png"/>
        <link rel="stylesheet" href="w3.css"/>
    </head>
    <body>
        <div class="w3-card-4">

            <header class="w3-container w3-blue">
              <h1>Pagina Inicial</h1>
            </header>
            
            <div class="w3-container">
                <ul class="w3-ul">
                    <li><a href="/compositores"> Compositores</a></li>
                    <li><a href="/periodo">Periodo</a></li>
                  </ul>                  
            </div>
            
            <footer class="w3-container w3-blue">
              <h5>Generated by EngWeb2024</h5>
            </footer>
            
        </div>
    </body>
</html>
`

    return html;
}


exports.compositoresPage = function (compositores,d) {
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Compositores Management</title>
        </head>
        <body>
            <div class="w3-card-4">

                <header class="w3-container w3-teal">
                    <h1>Students List
                    <a class="w3-btn w3-round w3-grey" href="/compositores/registo">+</a>
                    </h1>
                    
                </header>
        
                <div class="w3-container">
                    <table class="w3-table-all">
                        <tr>
                            <th>Id</th><th>Nome</th><th>Bio</th><th>Nascimento</th><th>Morte</th><th>Período</th>
                            <th>Actions</th>
                        </tr>
                `
    for(let i=0; i < compositores.length ; i++){
        pagHTML += `
                <tr>
                    <td>${compositores[i].id}</td>
                    <td><a href="/compositores/${compositores[i].id}">${compositores[i].nome}</a></td>
                    <td>${compositores[i].bio}</td>
                    <td>${compositores[i].dataNasc}</td>
                    <td>${compositores[i].dataObito}</td>
                    <td>${compositores[i].periodo}</td>
                    <td>
                        [<a href="/compositores/edit/${compositores[i].id}">Edit</a>][<a href="/compositores/delete/${compositores[i].id}">Delete</a>]
                    </td>
                </tr>
        `
    }

    pagHTML += `
            </table>
            </div>
                <footer class="w3-container w3-blue">
                    <h5>Generated by Engweb2024 in ${d} - [<a href="/">Return</a>]</h5>
                </footer>
            </div>
        </body>
    </html>
    `
    return pagHTML
}

exports.compositorPage = function(compositor, d ){
    var pagHTML = `
    <!DOCTYPE html>
    <html>
    <head>
        <title>Composito: ${compositor.nome}</title>
        <meta charset="utf-8"/>
        <link rel="icon" href="favicon.png"/>
        <link rel="stylesheet" href="w3.css"/>
    </head>
    <body>
        <div class="w3-card-4">
            <header class="w3-container w3-teal">
                <h1>Compositor ${compositor.nome}</h1>
            </header>

            <div class="w3-container">
                <ul class="w3-ul w3-card-4" style="width:50%">
                    <li><b>Nome: </b> ${compositor.nome}</li>
                    <li><b>Bio: </b> ${compositor.bio}</li>
                    <li><b>Data de nascimento: </b> ${compositor.dataNasc}</li>
                    <li><b>Data de obito: </b> ${compositor.dataObito}</li>
                    <li><b>Periodo: </b> ${compositor.periodo}</li>
                </ul>
            </div>
            
            <footer class="w3-container w3-teal">
                <address>Gerado por galuno::RPCW2022 em ${d} - [<a href="/compositores">Voltar</a>]</address>
            </footer>
        </div>
    </body>
    </html>
    `
    return pagHTML
}

exports.compositorDeletePage = function(compositor, d ){
    var pagHTML = `
    <!DOCTYPE html>
    <html>
    <head>
        <title>Compositor Eliminado</title>
        <meta charset="utf-8"/>
        <link rel="icon" href="favicon.png"/>
        <link rel="stylesheet" href="w3.css"/>
    </head>
    <body>
        <div class="w3-card-4">
            <header class="w3-container w3-teal">
                <h1>Compositor Eliminado</h1>
            </header>

            <div class="w3-container">
                <ul class="w3-ul w3-card-4" style="width:50%">
                    <li><b>Nome: </b> ${compositor.nome}</li>
                    <li><b>Bio: </b> ${compositor.bio}</li>
                    <li><b>Data de nascimento: </b> ${compositor.dataNasc}</li>
                    <li><b>Data de obito: </b> ${compositor.dataObito}</li>
                    <li><b>Periodo: </b> ${compositor.periodo}</li>
                </ul>
            </div>
            
            <footer class="w3-container w3-teal">
                <address>Gerado por galuno::RPCW2022 em ${d} - [<a href="/compositores">Voltar</a>]</address>
            </footer>
        </div>
    </body>
    </html>
    `
    return pagHTML
}






exports.compositor_form = function(d){
    return `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Compositores Form</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-purple">
                    <h2>Student Form</h2>
                </header>
            
                <form class="w3-container" method="POST">
                    <fieldset>
                        <legend>Metadata</legend>
                        <label>Id</label>
                        <input class="w3-input w3-round" type="text" name="id"/>
                        <label>Nome</label>
                        <input class="w3-input w3-round" type="text" name="nome"/>
                        <label>Bio</label>
                        <input class="w3-input w3-round" type="text" name="bio"/>
                        <label>Nascimento</label>
                        <input class="w3-input w3-round" type="text" name="dataNasc"/>
                        <label>Morte</label>
                        <input class="w3-input w3-round" type="text" name="dataObito"/>
                        <label>Período</label>
                        <input class="w3-input w3-round" type="text" name="periodo"/>
                    </fieldset>

                    <br/>
                    <button class="w3-btn w3-purple w3-mb-2" type="submit">Register</button>
                </form>

                <footer class="w3-container w3-purple">
                    <h5>Generated by EngWeb2023 in ${d} - [<a href="/compositores">Return</a>]</h5>
                </footer>
            </div>
    `
}

exports.compositorFormEdit = function(c, d){
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Student Form</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-purple">
                    <h2>Student Form</h2>
                </header>
            
                <form class="w3-container" method="POST">
                    <fieldset>
                        <legend>Metadata</legend>
                        <label>Id</label>
                        <input class="w3-input w3-round" type="text" name="id" readonly value="${c.id}"/>
                        <label>Nome</label>
                        <input class="w3-input w3-round" type="text" name="nome" value="${c.nome}"/>
                        <label>Bio</label>
                        <input class="w3-input w3-round" type="text" name="bio" value="${c.bio}"/>
                        <label>Nascimento</label>
                        <input class="w3-input w3-round" type="text" name="dataNasc" value="${c.dataNasc}"/>
                        <label>Morte</label>
                        <input class="w3-input w3-round" type="text" name="dataObito" value="${c.dataObito}"/>
                        <label>Período</label>
                        <input class="w3-input w3-round" type="text" name="periodo" value="${c.periodo}"/>
                    </fieldset>
                    `     

    pagHTML += `
                      
                    <br/>
                    <button class="w3-btn w3-purple w3-mb-2" type="submit">Register</button>
                </form>

                <footer class="w3-container w3-purple">
                    <h5>Generated by EngWeb2024 in ${d} - [<a href="/alunos">Return</a>]</h5>
                </footer>
            
            </div>
    `
    return pagHTML
}





exports.periodoPage = function (periodos,d) {
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Periodos Management</title>
        </head>
        <body>
            <div class="w3-card-4">

                <header class="w3-container w3-teal">
                    <h1>Periodos List
                    <a class="w3-btn w3-round w3-grey" href="/periodo/registo">+</a>
                    </h1>
                    
                </header>
        
                <div class="w3-container">
                    <table class="w3-table-all">
                        <tr>
                            <th>Id</th><th>Nome</th>
                        </tr>
                `
    for(let i=0; i < periodos.length ; i++){
        pagHTML += `
                <tr>
                    <td>${periodos[i].id}</td>
                    <td><a href='/periodo/${periodos[i].id}' >${periodos[i].nome}</a></td>
                    <td>
                        [<a href="/periodo/edit/${periodos[i].id}">Edit</a>][<a href="/periodo/delete/${periodos[i].id}">Delete</a>]
                    </td>
                </tr>
        `
    }

    pagHTML += `
            </table>
            </div>
                <footer class="w3-container w3-blue">
                    <h5>Generated by Engweb2024 in ${d} - [<a href="/">Return</a>]</h5>
                </footer>
            </div>
        </body>
    </html>
    `
    return pagHTML
}

exports.periodo_idPage = function(periodo, d ){
    var html = `
    <!DOCTYPE html>
    <html>
    <head>
        <title>Periodo: ${periodo.nome}</title>
        <meta charset="utf-8"/>
        <link rel="icon" href="favicon.png"/>
        <link rel="stylesheet" href="w3.css"/>
    </head>
    <body>
        <div class="w3-card-4">
            <header class="w3-container w3-teal">
                <h1>Periodo ${periodo.nome}</h1>
            </header>

            <div class="w3-container">
                <ul class="w3-ul w3-card-4" style="width:50%">
    `

    for (let i = 0; i < periodo.compositores.length; i++) {
        html += `
                    <li><a href="/compositores/${periodo.compositores[i]}">${periodo.compositores[i]}</a></li>
        `

    }


    html += `
                </ul>
            </div>
            
            <footer class="w3-container w3-teal">
                <address>Gerado por galuno::RPCW2022 em ${d} - [<a href="/periodo">Voltar</a>]</address>
            </footer>
        </div>
    </body>
    </html>
    `
    return html
}

exports.periodo_form = function(d){
    return `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Compositores Form</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-purple">
                    <h2>Student Form</h2>
                </header>
            
                <form class="w3-container" method="POST">
                    <fieldset>
                        <legend>Metadata</legend>
                        <label>Id</label>
                        <input class="w3-input w3-round" type="text" name="id"/>
                        <label>Nome</label>
                        <input class="w3-input w3-round" type="text" name="nome"/>
                        <label>Compositores</label>
                        <input class="w3-input w3-round" type="text" name="compositores"/>
                    </fieldset>

                    <br/>
                    <button class="w3-btn w3-purple w3-mb-2" type="submit">Register</button>
                </form>

                <footer class="w3-container w3-purple">
                    <h5>Generated by EngWeb2023 in ${d} - [<a href="/periodo">Return</a>]</h5>
                </footer>
            </div>
    `
}


exports.periodo_formEdit = function(periodo,d){
    return `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Compositores Form</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-purple">
                    <h2>Student Form</h2>
                </header>
            
                <form class="w3-container" method="POST">
                    <fieldset>
                    <legend>Metadata</legend>
                    <label>Id</label>
                    <input class="w3-input w3-round" type="text" name="id" readonly value="${periodo.id}"/>
                    <label>Nome</label>
                    <input class="w3-input w3-round" type="text" name="nome" value="${periodo.nome}"/>
                    <label>Compositores</label>
                    <input class="w3-input w3-round" type="text" name="compositores" value="${periodo.compositores}"/>
                    </fieldset>

                    <br/>
                    <button class="w3-btn w3-purple w3-mb-2" type="submit">Register</button>
                </form>

                <footer class="w3-container w3-purple">
                    <h5>Generated by EngWeb2023 in ${d} - [<a href="/periodo">Return</a>]</h5>
                </footer>
            </div>
    `
}


exports.periodoDeletePage = function(periodo, d ){
    var pagHTML = `
    <!DOCTYPE html>
    <html>
    <head>
        <title>Periodo Eliminado</title>
        <meta charset="utf-8"/>
        <link rel="icon" href="favicon.png"/>
        <link rel="stylesheet" href="w3.css"/>
    </head>
    <body>
        <div class="w3-card-4">
            <header class="w3-container w3-teal">
                <h1>Periodo Eliminado</h1>
            </header>

            <div class="w3-container">
                <ul class="w3-ul w3-card-4" style="width:50%">
                    <li><b>id: </b> ${periodo.id}</li>
                    <li><b>Nome: </b> ${periodo.nome}</li>
                </ul>
            </div>
            
            <footer class="w3-container w3-teal">
                <address>Gerado por galuno::RPCW2022 em ${d} - [<a href="/periodo">Voltar</a>]</address>
            </footer>
        </div>
    </body>
    </html>
    `
    return pagHTML
}



exports.errorPage = function(errorMessage, d){
    return `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Error page</title>
        </head>
        <body>
            <div class="w3-card-4">

                <header class="w3-container w3-teal">
                    <h1>Error</h1>
                </header>

                <div class="w3-container">

                <p>${d} ERRO: ${errorMessage}</p>

                </div>

                <footer class="w3-container w3-teal">
                    <address>Generated by EngWeb2023 in ${d} - [<a href="/"<Voltar</a>]</address>
                </footer>
            </div>
        </body>
    </html>
    `
}


